version: 2

builds:
  - id: jirka
    main: ./app
    binary: jirka
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.revision={{.Tag}}-{{.ShortCommit}}-{{ trimsuffix (replace (replace .CommitDate "-" "") ":" "") "Z" }}

archives:
  - id: jirka
    builds:
      - jirka
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

brews:
  - repository:
      owner: cnwv
      name: homebrew-apps
    directory: Formula
    homepage: https://github.com/cnwv/jirka
    description: TUI dashboard for Jira tickets
    license: MIT
